name: glue
description: A complete Glue programming language interpreter for Dart - Lisp-inspired with modern features.
version: 0.1.0
homepage: https://github.com/gev/glue
repository: https://github.com/gev/glue
issue_tracker: https://github.com/gev/glue/issues

environment:
  sdk: '^3.9.2'

resolution: workspace

dependencies:
  petitparser: any
  fast_immutable_collections: any

dev_dependencies:
  lints: ^6.0.0
  test: any
